### ISSUE TITLE
Multiple devices

### ISSUE THREAD

**Issue by advatar** [netreconlab/CareKitSample-ParseCareKit#9] opened 2020-11-01 15:27 UTC
I am trying to run this on two different devices (logging into the same parse account) in the Simulator but I get nothing to sync. Is this use case supported? What I was to not call populateSampleData(), under the assumption that my tasks would be synchronised from the "cloud" (localhost).

Also, there is a parse error when receiving OCKOutcome values. Typical console log would be:

User is already signed in. Autosync is set to Optional(true)
New session state: WCSessionActivationState
2020-11-01 16:23:25.989200+0100 OCKSample[53471:7998241] [WC] WCSession counterpart app not installed
2020-11-01 16:23:26.135940+0100 OCKSample[53471:7998240] [] nw_protocol_get_quic_image_block_invoke dlopen libquic failed
An unexpected error occured ParseError code=-1 error=cannot decode error
Finished pulling default revision classes
Successful sync with Cloud!
Finished pulling default revision classes
Completed sync in DailyPageViewController

**Comment by cbaker6** [comment] 2020-11-01 23:01
> What I was to not call populateSampleData(), under the assumption that my tasks would be synchronised from the "cloud" (localhost).

Yes, you are correct, the second device shouldn’t populate sample data as the original data from the first device will be pulled from the Cloud. If you populate sample data on a second device, it’s creating duplicate objects with different objectIds (so this will cause issues). This is because the sample app is intended to show how to get started with one device, and needs to be modified by the developer to turn it into a deployable app.

> 2020-11-01 16:23:25.989200+0100 OCKSample[53471:7998241] [WC] WCSession counterpart app not installed
This is not a problem, the app can work with watchOS, it’s currently not detecting a connection to a watch.

The rest of the errors should be fine as long as you are getting, “Successful sync with Cloud!”

**Comment by advatar** [comment] 2020-11-03 13:25
But I do not see any tasks in DailyPageViewController on the second device.

**Comment by cbaker6** [comment] 2020-11-03 16:16
@advatar thanks for pointing this out. This was a decoding error due to some changes in ParseCareKit. It has since been fixed in https://github.com/netreconlab/ParseCareKit/pull/56

**Comment by cbaker6** [comment] 2020-11-03 16:33
Feel free to close if it works after you try the update

**Comment by advatar** [comment] 2020-11-03 19:00
I made a fresh clone, updated swift packages but get:

020-11-03 19:59:16.777481+0100 OCKSample[58772:4212713] [] nw_protocol_get_quic_image_block_invoke dlopen libquic failed
Parse signup successful _User ({"username":"UpstreamFix","password":"ThisIsAStrongPass1!","objectId":"ddkPN6iWX0Uv3X8zKfRMl4QrJwfCjZru","updatedAt":{"__type":"Date","iso":"2020-11-03T18:59:16.814Z"},"ACL":{},"createdAt":{"__type":"Date","iso":"2020-11-03T18:59:16.814Z"}})
New session state: WCSessionActivationState
2020-11-03 19:59:17.084076+0100 OCKSample[58772:4212718] [WC] -[WCSession onqueue_handleUpdateSessionState:]_block_invoke dropping as pairingIDs no longer match. pairingID (null), client pairingID: (null)
2020-11-03 19:59:17.090088+0100 OCKSample[58772:4212718] [WC] WCSession is not paired
Added tasks into HealthKitPassthroughStore!
2020-11-03 19:59:17.113630+0100 OCKSample[58772:4212714] [CareKitStore] Failed to automatically synchronize.
2020-11-03 19:59:17.114017+0100 OCKSample[58772:4212713] [CareKitStore] Failed to observe HealthKit sample type
2020-11-03 19:59:17.114208+0100 OCKSample[58772:4212713] [CareKitStore] Error: Authorization not determined
2020-11-03 19:59:17.114638+0100 OCKSample[58772:4212714] [CareKitStore] Error: Sync failed: Already busy synchronizing!
2020-11-03 19:59:17.126799+0100 OCKSample[58772:4212714] [CareKitStore] Failed to automatically synchronize.
2020-11-03 19:59:17.127005+0100 OCKSample[58772:4212714] [CareKitStore] Error: Sync failed: Already busy synchronizing!
2020-11-03 19:59:18.999526+0100 OCKSample[58772:4212713] Metal API Validation Enabled

**Comment by cbaker6** [comment] 2020-11-03 19:03
You can try stoping the app and running again. You can also delete the app from the simulator and reinstall

**Comment by cbaker6** [comment] 2020-11-03 19:33
There's a bug I noted about the first login (this is your second device the first time it logs into Parse) in the last PR, https://github.com/netreconlab/CareKitSample-ParseCareKit/pull/11#issue-514910021

After the first run, stop the app in Xcode and run again. You won't see the issue anymore afterwards. This has something to do with programmatically logging in and the OCKSynchronizer not being established before the login is complete. When you write your app with an actual signup/login screen, you probably won't have this issue.

**Comment by advatar** [comment] 2020-11-03 20:37
I have been doing all kinds of resets and now the second device does get the tasks from the cloud. However, I am getting 

An unexpected error occured ParseError code=-1 error=cannot decode error

I tracked that down to an incoming OCKOutcome so the state of the tasks and the graphs do not update across devices.

**Comment by advatar** [comment] 2020-11-03 21:18
Now, parse-hipaa is logging

parse_1      |   Result: undefined {"className":"Outcome","triggerType":"afterSave","user":"SSXF2XN8MNgIY6EMx0OgrmLEksuB2CTA"}
parse_1      | error: Parse error:  Invalid session token {"code":209,"stack":"Error: Invalid session token\n    at Object.getAuthForSessionToken (/parse-server/lib/Auth.js:114:11)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"}
parse_1      | error: Parse error:  Invalid session token {"code":209,"stack":"Error: Invalid session token\n    at Object.getAuthForSessionToken (/parse-server/lib/Auth.js:114:11)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"}

And in Xcode

User is already signed in. Autosync is set to Optional(true)
New session state: WCSessionActivationState
2020-11-03 22:17:10.545096+0100 OCKSample[39121:522869] [WC] WCSession counterpart app not installed
2020-11-03 22:17:10.648841+0100 OCKSample[39121:522863] [] nw_protocol_get_quic_image_block_invoke dlopen libquic failed
Error in Outcome.tombstsone(). ParseError code=209 error=Invalid session token
Error in Outcome.tombstsone(). ParseError code=209 error=Invalid session token
Error in Outcome.tombstsone(). ParseError code=209 error=Invalid session token

**Comment by cbaker6** [comment] 2020-11-03 21:58
You are getting "invalid session token" on both which means you probably typed `docker-compose down` which destroyed the database and your app is attempting to connect with an old session token from Keychain, that isn't related to the new database created with `docker-compose up`.

The solution is to delete the app in the simulator. A new session token will be created when the app signs up or logs in

**Comment by advatar** [comment] 2020-11-03 23:18
Might be the case, have been doing "Erase all content" etc.   Regardless, when I manage to get the token right I still can not get Outcomes to sync. Been stepping through the debugger and it always fails for Outcome with "An unexpected error occured ParseError code=-1 error=cannot decode error".

**Comment by cbaker6** [comment] 2020-11-04 14:33
> Might be the case, have been doing "Erase all content" etc. 

Most of the time you shouldn't need to docker-compose down or wipe the database. An easier way is to just delete the user entry in the Parse Dashboard, and then delete the app on device. It will automatically generate a new session token when it signs up again

> Regardless, when I manage to get the token right I still can not get Outcomes to sync. Been stepping through the debugger and it always fails for Outcome with "An unexpected error occured ParseError code=-1 error=cannot decode error".

This should be fixed with latest update I just made. Let me know if it works. Note that the bug/comment I mentioned earlier about the first login is still there, but if you have previous tasks completed and they impact adherence, you will see the rings at the top for the respective days close when the sync is completed.

**Comment by cbaker6** [comment] 2020-11-05 15:27
The latest merge adds a "sync button" to the top right of the "Patient Care" page. When logging in for the first time on the second device, the synced cards may not show (the adherence rings may close though). Simply tap the sync button and all of the synced task will show. If the sync button turns to a red color, tap sync again your second device should be in working state and fully synced.

**Comment by cbaker6** [comment] 2020-11-07 12:18
You shouldn’t see anymore errors in the console log with the exception of the watchOS one that shows up if you didn’t run the OCKSample app for watchOS yet.

**Comment by cbaker6** [comment] 2020-11-08 15:29
Update when logging in on the second device and synced data doesn’t show, requiring the sync button to be pressed. This is NOT a bug and is expected behavior. This is because the each Card/Task is linked to the OCKSynchronization manager, but not the DailyPageViewController itself. During the initial login, no tasks are in the data store and therefore no cards to display on the DailyPageViewController. When data/tasks/outcomes/etc are finally pulled from the cloud, there’s no linked cards. So the DailyPageViewController needs to be reloaded to creat the cards.

There can be fixes for this, for example, sending a notification to reload the view after first sync

**Comment by advatar** [comment] 2020-11-09 15:28
Nice, now it works. Regarding the sync, will updates be pushed or should I setup a timer to pull changes?

**Comment by cbaker6** [comment] 2020-11-09 15:42
By default, I set auto sync on the remote, so all synching is managed by the OCKStore which typically pushes immediately, but has it's own intelligence. You can set `auto` to `false` on the `ParseRemoteSynchronizationManager` and call:

```swift
coreDataStore.synchronize { error in
   print(error?.localizedDescription ?? "Successfully synced with remote!")
}
```

You can also call the above when auto is on, but you may get, "already syncing". 

If you are using this app as a baseline, then a better way to request a sync is just to post a notification:

```swift
DispatchQueue.main.async {
      NotificationCenter.default.post(.init(name: Notification.Name(rawValue: "firstLoginSyncComplete")))
}
```

**Comment by advatar** [comment] 2020-11-09 17:36
I have noticed the auto sync for pushing to Parse at the point of creation but I mean the other way, for another idle device to get notified there is new data.

**Comment by cbaker6** [comment] 2020-11-09 17:53
You would need to send a Push notification from the parse-server side. You can look into push notifications here: https://docs.parseplatform.org/ios/guide/#push-notifications

Push notifications aren't supported with the current version of Parse-Swift, but they will be soon.

Depending on what devices you are trying to sync, you can look at the `OCKWatchSample Extension` in this repo. Running the `OCKWatchSample` target in this repo automatically keeps the watch and iPhone in sync through parse-hipaa. This works by the watch and iPhone sending notifications telling the other to pull from the cloud when there's new data.

A little more detail from the readme:

> NEW - Just like the [What's New in CareKit](https://developer.apple.com/videos/play/wwdc2020/10151/) WWDC20 video, this app syncs between the AppleWatch (setting the flag in `ExtensionDelegate.swift` and `AppDelegate.swift` to  `syncWithCloud = false`. Different from the video, setting `syncWithCloud = true` (default behavior) in the aforementioned files syncs iOS and watchOS to a Parse Server.

**Closed** 2020-11-09 23:42 UTC

**Comment by cbaker6** [comment] 2020-11-19 21:37
If you don't want to use push notifications, see https://github.com/netreconlab/CareKitSample-ParseCareKit/issues/27#issuecomment-726383181
